services:
  sales-db:
    container_name: sales-db
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sales_db
    volumes:
      - sales-db:/var/lib/postgresql/data
    restart: unless-stopped