services:
  sales-db:
    container_name: sales-db
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sales_db
    volumes:
      - sales-db:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: sales-db-pgadmin
    image: dpage/pgadmin4
    depends_on:
      - sales-db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    restart: unless-stopped

volumes:
  sales-db: